from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, Field


class PlaybookStep(BaseModel):
    """Single action recorded from the visual browser flow."""

    id: str = Field(..., description="Stable identifier generated by the recorder")
    action: Literal[
        "navigate",
        "click",
        "input",
        "extract",
        "wait",
        "http_request",
        "transform",
    ]
    target: str | None = Field(
        None, description="CSS/XPath selector, URL, or data address the action interacts with"
    )
    value: str | None = Field(None, description="Value associated with the action, if any")
    metadata: dict[str, Any] = Field(default_factory=dict)


class RecordingCreate(BaseModel):
    name: str
    description: str | None = None
    steps: list[PlaybookStep] = Field(default_factory=list)


class Recording(RecordingCreate):
    id: int
    created_at: datetime

    model_config = {
        "from_attributes": True,
    }


class JobSchedule(BaseModel):
    cron_expression: str = Field(
        ..., description="Standard five-field cron expression that drives APScheduler"
    )
    timezone: str = Field(default="UTC")


class JobCreate(BaseModel):
    name: str
    description: str | None = None
    recording_id: int
    schedule: JobSchedule
    payload: dict[str, Any] | None = Field(
        default=None,
        description="Optional structured payload used to parameterise the playbook at runtime",
    )


class Job(JobCreate):
    id: int
    created_at: datetime

    model_config = {
        "from_attributes": True,
    }


class ExecutionStatus(str, Enum):
    PENDING = "pending"
    RUNNING = "running"
    SUCCESS = "success"
    FAILED = "failed"


class ExecutionResult(BaseModel):
    logs: list[str] = Field(default_factory=list)
    outputs: dict[str, Any] = Field(default_factory=dict)
    artifacts: dict[str, Any] = Field(default_factory=dict)


class Execution(BaseModel):
    id: int
    job_id: int
    status: ExecutionStatus
    started_at: datetime
    finished_at: datetime | None
    result: ExecutionResult

    model_config = {
        "from_attributes": True,
    }
